# Generated by Django 5.0.4 on 2024-06-05 02:58

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_provider_address_alter_vet_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[('LaPlata', 'La Plata'), ('Berisso', 'Berisso'), ('Ensenada', 'Ensenada')], default=app.models.City['LaPlata'], max_length=50),
        ),
    ]
